### PR TITLE
Hints 

### PR DESCRIPTION
**Pull request by AakarM1**
Hints problem solved

### CODE REVIEW

**Comment by Fir121** [comment]
You have committed your venv...

**Comment by Fir121** [comment]
And refer last PR for some comments on making an env, lets have that in this PR

**Comment by Fir121** [comment]
I'd suggest a delete and re-fork, new clone and apply the needed changes, it was probably only a few lines of code?

**Review by Sanvit-Katrekar — CHANGES_REQUESTED** [review]
Major bug: Points deduction on taking hints does not work
Still need to fix PyJWT issue, remove jwt from requirements.txt and only keep PyJWT
In .gitignore remove tracking for db.sqlite3
mouseenv is added to .gitignore but still committed, need to delete
Suggestion for no_hint page, in general avoid using pure colors like pure red here, try a lighter shade I suggest using #dc3545

**Pull request closed without merging**
